#!/data/data/com.termux/files/usr/bin/bash

SOURCE="$HOME/tui/script/start"
TARGET="$HOME/start"
ALIAS_LINE="alias starti3='./start'"

if [ -f "$SOURCE" ]; then
    cp "$SOURCE" "$TARGET"
    echo "[info] Copied 'start' script to home directory."
else
    echo "[info] Source file not found: $SOURCE"
    exit 1
fi

chmod +x "$TARGET"
echo "[info] Made 'start' executable."

if [ -f "$HOME/.zshrc" ]; then
    RCFILE="$HOME/.zshrc"
elif [ -f "$HOME/.bashrc" ]; then
    RCFILE="$HOME/.bashrc"
else
    RCFILE="$HOME/.bashrc"
    touch "$RCFILE"
fi


if ! grep -Fxq "$ALIAS_LINE" "$RCFILE"; then
    echo "$ALIAS_LINE" >> "$RCFILE"
    echo "[info] Alias added to $RCFILE"
else
    echo "[info] Alias already exists in $RCFILE"
fi

PADDING=" " 
MESSAGE="󱦟 i3 has been installed. You can start it by typing starti3"

echo
echo -e "${PADDING}\033[1;32m$MESSAGE\033[0m${PADDING}"
